### ISSUE TITLE
Setup Initial Testing Framework

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#12]
Establish a framework for testing the chatbot's responses and functionality.

**Comment by HusseinnSolimann** [comment]
Hello Team,

I have set up a suite of automated tests for our WhatsApp GPT Bot to ensure functionality and to catch issues early in the development process. However, upon running the tests, I encountered an ImportError during the collection phase. The tests are unable to locate the src module, which is essential for testing our application's functionality.

Could anyone please take a look at the test setup and help identify the cause of the import errors? Any suggestions would be greatly appreciated to resolve this issue promptly.

**Comment by adnanbhanji** [comment]
Yes, on it right now. Trying to figure out the issue with the paths.

**Comment by adnanbhanji** [comment]
Update: We were able to set up the initial testing framework with the MLOps Engineer, and in the next iteration will add it in the workflows and ensure it's automated.
