### ISSUE TITLE
Create a function that returns the final result as the PDF filled with all the answers. 

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#22]

**Comment by KhaledAkel** [comment]
Done.

I made a simple function that takes a specific template (as String) and the variables extracted from the conversation from GPT4, like the CO2 emissions ... The variables are saved in HashMap. 
The function takes these Parameters and generate a pdf from scratch.
For Next Iteration, we need to work on the report design, and modify the functions to fill in the new form.
