### ISSUE TITLE
Midterm feedback

### ISSUE THREAD

**Issue by miguelgfierro** [adnanbhanji/EU-Chatbot-Reco-System#24]
- [x] Merge to main in every feature you make
- [x] Simplify the root folder https://github.com/adnanbhanji/EU-Chatbot-Reco-System/tree/gpt-bot something like libraries, examples, tests, docs
- [x] It is ok to have feature branches, but when you are finished you need to merge to main.
- [x] remove config files https://github.com/adnanbhanji/EU-Chatbot-Reco-System/tree/gpt-bot/config/__pycache__ 
- [x] Create a release for every delivery point https://github.com/miguelgfierro/project_template/releases/tag/0.1.1
- [x] Add the deps https://github.com/adnanbhanji/EU-Chatbot-Reco-System/blob/gpt-bot/requirements.txt
- [x] Binary files shouldn't be in the repo https://github.com/adnanbhanji/EU-Chatbot-Reco-System/blob/gpt-bot/src/34654431185_report_20240221154804.pdf
- [x] If you have a demo, you can create a gif or a YouTube video that you can link in the README
- [x] Use the assistant API in OpenAI, where you can give the bot a script and then the bot will follow the script. You can compare this with the hardcoded workflow.

**Comment by smorenolasa1** [comment]
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/e359ab74-1893-486b-8e34-50475f58e5e7)

Used the assistant API in OpenAI to give the bot a script. 
Script given:  "You are a helpful assistant knowledgeable about farming practices, designed to collect detailed reports from farmers about their farm conditions. Please ensure you collect accurate information on the farm's name, location, size, and any issues they're facing."

Added changes in commands.py of the watsapp folder:
https://github.com/adnanbhanji/EU-Chatbot-Reco-System/tree/gpt-assistantAPI-flow1

**Comment by smorenolasa1** [comment]
Also changed the structure of the conversation flow to be handled by the LLama2 model through the Replicate API using the same script context:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/a42f5b29-4cf6-463b-b7b7-44b1d695c3ad)
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/5b5c2d13-2651-49fd-8ecf-a19a7b6a5fb2)

Modified function:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/bc13aa4e-2f5a-4a7f-8626-48149457dafa)
