### ISSUE TITLE
Update Conversation Flows

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#26]
Modify the conversation flows in our chatbot to accommodate LLama's response format and input requirements.

**Comment by smorenolasa1** [comment]
For this issue, we are planning on adding a flow control mechanism to decide whether to proceed with report generation or consult LLaMA-2 for an answer.
We have to incorporate logic to handle the "start report" command specifically, while other inputs are processed through LLaMA-2.

**Comment by smorenolasa1** [comment]
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/41eea9eb-acc6-49ab-8493-843c0bebf9e3)
Managed to end conversation flow

**Comment by smorenolasa1** [comment]
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/773bba1f-7e94-4bd2-852d-c3e847fc65c5)
Managed to ask a question during the conversation flow
Modified the msgrcvd function:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/8c9ad7b1-67f0-4b0a-b363-bac10b206162)
Added a new function to call the llama model when a question is asked:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/183c3b84-0261-4056-bc07-641e80274978)

**Comment by smorenolasa1** [comment]
Modified the code to send the details of the report at the end:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/50ba5ccf-d407-40a1-9d74-d7712a0e4470)

Modified existing process_answer function tu handle the summary generation:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/2e898afa-9b30-448c-84a8-0d722b4864a5)

Created a function to prepare the summary:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/13e42b0d-d139-4db8-890f-44627f27094c)

**Comment by smorenolasa1** [comment]
modified funciton to create a pdf:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/6b40faf2-097e-46ee-be95-be1d357d9082)
pdf generated:
![image](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/117740777/536f211f-4664-4796-840c-ad78d73dc7ef)

**Comment by adnanbhanji** [comment]
Great work, passes tests and achieves purpose.
