### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#30]
Update the project documentation to include information about the LLama bot integration, including setup instructions, usage guidelines, and any relevant technical details.

**Comment by smorenolasa1** [comment]
Updated the Readme in the llama_whatsapp folder to show all the set up steps for collegues to try. I will update the user guidelines shortly.

**Comment by smorenolasa1** [comment]
Updated read.me files with all the demos, updated the requirements.txt for both the gpt and llama2, and the getting_started.md, api_reference.md and userguide. md for the llama2 bot to show how to set it up and get it started.

**Comment by adnanbhanji** [comment]
Constantly updating the documentation as we iterate and progress.
