### ISSUE TITLE
Enhance pdf output

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#32]
Ensure the output of the form is a well structured pdf.

**Comment by KhaledAkel** [comment]
Done,
I have modified the older functions in the pdfDesign branch. Now, the PDF output is well-structured official document with a place to sign and certify, including all the information we need for the report. There is a pdfDesign.py file which we can use for testing the conversation flow, and pdfDesign-V2.py is for official use after deployment.

**Comment by adnanbhanji** [comment]
![Screenshot 2024-04-04 at 12 44 07 in the afternoon](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/81592934/89aabedb-7f92-47d7-9c78-2304f9df7962)
![Screenshot 2024-04-04 at 12 44 03 in the afternoon](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/81592934/7922355f-079d-4b38-ae55-870e91e72a2d)

Output of pdf, with html, css design.
