### ISSUE TITLE
Ensure data collection occurs seamlessly after each conversation, then get's stored on the blockchain framework. 

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#33]

**Comment by beaamoo** [comment]
Moved to Azure Storage to be able to establish a fully functional and tested solution and deployment, leaving the possibility of blockchain integration for a future iteration.

**Comment by beaamoo** [comment]
**Completed Updates:**
- Architecture Design: The architecture design has been updated. The revised design can now be viewed in the documentation.
- Deployment Workflow Setup: I've successfully set up the deployment workflow. This setup should streamline our future deployment processes.

**Pending Task:**
- Azure Resource Group Issue: There's an outstanding issue with creating a resource group under our current - Azure subscription. This problem needs to be addressed to ensure our infrastructure is fully operational.

**Action Requested:**
- Please review the updated architecture design in the docs to ensure it aligns with our project goals.
- Assistance with troubleshooting and fixing the issue related to Azure resource group creation would be highly appreciated. Any insights or suggestions on this matter would be valuable.

**Comment by adnanbhanji** [comment]
Architecture update: AWS Lambda functions and EC2 instance for the API
