### ISSUE TITLE
Ensure PDF output captures conversation flow.

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#49]

**Comment by KhaledAkel** [comment]
The function just needs a hashmap that captures all the required info from conversation with the chatbot. check the file for more.

**Comment by adnanbhanji** [comment]
Latest update for custom bot: 


![Screenshot 2024-04-04 at 12 44 07 in the afternoon](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/81592934/23c761fe-f1b8-43f5-8c5e-d61128ea38d3)
![Screenshot 2024-04-04 at 12 44 03 in the afternoon](https://github.com/adnanbhanji/EU-Chatbot-Reco-System/assets/81592934/1a5b2b7a-032c-4b42-b728-f8232df0d0d2)
