### ISSUE TITLE
Research Azure Bot Deployment

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#51]

**Comment by beaamoo** [comment]
I've made progress on our project's infrastructure and workflow setup on the deployment branch:

- **Architecture Design Update**: I have revised our architecture design, which is now documented and can be viewed in the docs section. This update aims to streamline our system's structure and improve overall efficiency.

- **Deployment Workflow Setup**: The deployment workflow has been established, ensuring a smoother transition and automation for our deployment processes.

**Remaining Task:**

- **Azure Resource Group Issue**: There is an outstanding issue where we are unable to create a resource group under our current Azure subscription. This needs to be addressed to ensure our infrastructure is correctly set up in the cloud.

**Action Requested:**

- Please review the updated architecture design in the documentation and the deployment workflow setup.
- Any assistance or insights into resolving the Azure Resource Group creation issue would be appreciated.

**Comment by adnanbhanji** [comment]
Final change: Azure to AWS. 

We chose AWS over Azure primarily due to the advantages offered by AWS's free tier. In terms of size and resources, AWS provided a more generous free tier allowance compared to Azure, which allowed us to experiment with a wider range of services without incurring costs. Additionally, AWS offered more data storage capacity within its free tier, which was essential for our needs. Furthermore, Azure's limitations on creating resource groups and other restrictions with student accounts posed obstacles to experimentation and learning process. AWS's support for creating resource groups, along with the flexibility to utilize services like Lambda functions and EC2 instances, made it the preferred choice for our projects and educational endeavors.
