### ISSUE TITLE
Finalize requirements and data sources / API's

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#6]

**Comment by beaamoo** [comment]
After thorough review and discussion, we have finalised the requirements and identified the necessary data sources/APIs for the project. The relevant architecture and data schema documentation has been updated to reflect these decisions. However, the specific parameters and configurations for the API in the documentation is still to be completed. Moving forward, we'll implement these specifications to ensure our project aligns with the established goals and integrates seamlessly with the chosen data sources/APIs.
