### ISSUE TITLE
Integrate GPT-4 API

### ISSUE THREAD

**Issue by adnanbhanji** [adnanbhanji/EU-Chatbot-Reco-System#9]
Implement the integration of GPT-4 API for natural language processing capabilities.

**Comment by KhaledAkel** [comment]
The GPT4 is integrated however it needs more improvements.

**Comment by adnanbhanji** [comment]
We can close this issue as we have accomplished the connection with the GPT-4 API. Further issues will delve deeper into the technicalities regarding this.
